import '../../api/Activities/server/publications';
import '../../api/Activities/server/methods';
import '../../api/Files/server/publications';
import '../../api/Files/server/methods';
import '../../api/Files/server/aws';
import '../../api/OAuth/server/methods';
import '../../api/Users/server/methods';
import '../../api/Users/server/publications';
import '../../api/Organisations/server/publications';
